services:
  db:
    image: postgres:16
    container_name: busan-timing-data-collector-db
    environment:
      POSTGRES_DB: busan_timing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
